homework 21-11-2022: implemented calculator based on the wait promise
pvukmanovic-pannonians/pannonians-obuka pull request #44
Opened 2022-11-22 16:28 UTC by GajicDusan

2022-11-23 14:03 UTC, pvukmanovic-pannonians approved these changes

2022-11-24 12:44 UTC, pvukmanovic-pannonians requested changes
Ajde da ubacimo .gitignore fajl u root ova dva foldera, koji ce imati sadrzaj isti kao kod mene u folderu:
``` text
node_modules
```
takodje plz obrisi foldere node_modules

2022-11-24 15:03 UTC, GajicDusan commented
Done. Javljaj ako treba jos stogodj. :)

2022-11-25 20:14 UTC, pvukmanovic-pannonians approved these changes
LGTM

2022-11-28 09:37 UTC, merged